### ISSUE TITLE
possible EventEmitter memory leak detected

### ISSUE THREAD

**Issue by aheritier** [statusdashboard/statusdashboard#14]
On my instance I saw this error message. It may explain why the server crashes regularly if there is a memory leak...

(node) warning: possible EventEmitter memory leak detected. 11 listeners added. Use emitter.setMaxListeners() to increase limit.
Trace: 
    at EventEmitter.<anonymous> (events.js:126:17)
    at SocketNamespace.<anonymous> (/home/swfdashboard/dashboard/server.js:63:7)
    at SocketNamespace.<anonymous> (events.js:64:17)
    at SocketNamespace.emit (/home/swfdashboard/dashboard/node_modules/socket.io/lib/namespace.js:170:40)
    at /home/swfdashboard/dashboard/node_modules/socket.io/lib/namespace.js:220:14
    at Memory.join (/home/swfdashboard/dashboard/node_modules/socket.io/lib/stores/memory.js:164:9)
    at SocketNamespace.handlePacket (/home/swfdashboard/dashboard/node_modules/socket.io/lib/namespace.js:217:18)
    at /home/swfdashboard/dashboard/node_modules/socket.io/lib/manager.js:346:32
    at Client.count (/home/swfdashboard/dashboard/node_modules/socket.io/lib/stores/memory.js:254:3)
    at /home/swfdashboard/dashboard/node_modules/socket.io/lib/manager.js:336:32

**Comment by obazoud** [comment]
I update socket.io
and I add a new api http://statusdashboard.nodester.com/api/uptime that returns uptime:

```
{
startupTime: 1317063168566
now: 1317646889496
uptime: 583720930
human: "6 days ago"
}
```

as you can see, now statusdashboard can live longer

**Comment by obazoud** [comment]
Guillermo Rauch, creator of socket.io :

> This affects only the XHR transports. It's not really a memory leak because 
> upon a full disconnect the connection gets cleared (...)

http://groups.google.com/group/socket_io/browse_thread/thread/ffa1ab005c64676e
http://stackoverflow.com/questions/4884990/socketio-node-recovering-lost-connections
