### ISSUE TITLE
journey error

### ISSUE THREAD

**Issue by FLYBYME** [statusdashboard/statusdashboard#25]
Im getting this error can anyone point out whats wrong?

TypeError: undefined is not a function
    at /tmp/9968177f-dfd6-9a83-8189-1e65e71a6ebc/node_modules/journey/lib/journey.js:348:32
    at find (/tmp/9968177f-dfd6-9a83-8189-1e65e71a6ebc/node_modules/journey/lib/journey.js:284:17)
    at /tmp/9968177f-dfd6-9a83-8189-1e65e71a6ebc/node_modules/journey/lib/journey.js:279:39
    at Object.journey.Router.validateRoute (/tmp/9968177f-dfd6-9a83-8189-1e65e71a6ebc/node_modules/journey/lib/journey.js:221:37)
    at find (/tmp/9968177f-dfd6-9a83-8189-1e65e71a6ebc/node_modules/journey/lib/journey.js:276:22)
    at /tmp/9968177f-dfd6-9a83-8189-1e65e71a6ebc/node_modules/journey/lib/journey.js:279:39
    at Object.journey.Router.validateRoute (/tmp/9968177f-dfd6-9a83-8189-1e65e71a6ebc/node_modules/journey/lib/journey.js:221:37)
    at find (/tmp/9968177f-dfd6-9a83-8189-1e65e71a6ebc/node_modules/journey/lib/journey.js:276:22)
    at /tmp/9968177f-dfd6-9a83-8189-1e65e71a6ebc/node_modules/journey/lib/journey.js:279:39
    at Object.journey.Router.validateRoute (/tmp/9968177f-dfd6-9a83-8189-1e65e71a6ebc/node_modules/journey/lib/journey.js:221:37)

**Comment by obazoud** [comment]
Hi,

Looks strange, have you change something ?

Olivier.

**Comment by FLYBYME** [comment]
I have not changed anything.

I am running node 0.8.5

**Comment by obazoud** [comment]
I test with 0.4.x and 0.6.x, not yet with 0.8.x.

Olivier.

**Comment by FLYBYME** [comment]
Time for new tests?

Anyways thanks.
Tim

**Comment by FLYBYME** [comment]
I ended up removing journey and going with raw node server and replacing paperboy with send.

Why did you not use express as the server?
