### ISSUE TITLE
404 for History plugin and history icon with vanilla install and demo env

### ISSUE THREAD

**Issue by Esya** [statusdashboard/statusdashboard#51]
I wanted to clone your repo and play a bit with it but it doesnt seem to work that well for me. For some reason, the Plugin icon and `/api/history/toolbar-popin.html` give me a 404 all the time.

**Note** it works fine with `/ap/history/all` though.
1. `git clone` the repository
2. `npm install`
3. `export APP_ENV=demo`
4. `./bin/statusdashboard`

**Log here** 

```
3 Aug 13:34:58 - Loading settings: demo
3 Aug 13:34:58 - Express server static directory: /Users/tfoureur/Documents/src-git/statusdashboard/public
3 Aug 13:34:58 - Server running at http://0.0.0.0:8080
   info  - socket.io started
3 Aug 13:34:58 - Refreshing status board...
3 Aug 13:34:58 - Server started.
Creating the plugin: /Users/tfoureur/Documents/src-git/statusdashboard/plugins/history/history_plugin.js
3 Aug 13:34:58 - Add GET route contribution: /^\/api\/history\/service\/([a-z\-]+)$/
3 Aug 13:34:58 - Add GET route contribution: /^\/api\/history\/all\/([a-z\-]+)$/
3 Aug 13:34:58 - Add GET route contribution: /^\/api\/history\/all$/
3 Aug 13:34:58 - Add static contribution: history, /Users/tfoureur/Documents/src-git/statusdashboard/plugins/history/public
3 Aug 13:35:04 - Refreshing status board...
127.0.0.1 - - [Sat, 03 Aug 2013 12:35:05 GMT] "GET /api/history/toolbar-popin.html HTTP/1.1" 404 - "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/28.0.1500.95 Safari/537.36"
3 Aug 13:35:05 - Error: Can't set headers after they are sent.
                  at ServerResponse.OutgoingMessage.setHeader (http.js:704:11)
                  at ServerResponse.res.setHeader (/Users/tfoureur/Documents/src-git/statusdashboard/node_modules/express/node_modules/connect/lib/patch.js:62:20)
                  at /Users/tfoureur/Documents/src-git/statusdashboard/node_modules/express/node_modules/connect/lib/middleware/static.js:162:37
                  at Object.oncomplete (fs.js:107:15)
3 Aug 13:35:05 - Error: Can't set headers after they are sent.
                  at ServerResponse.OutgoingMessage.setHeader (http.js:704:11)
                  at ServerResponse.res.setHeader (/Users/tfoureur/Documents/src-git/statusdashboard/node_modules/express/node_modules/connect/lib/patch.js:62:20)
                  at /Users/tfoureur/Documents/src-git/statusdashboard/node_modules/express/node_modules/connect/lib/middleware/static.js:168:11
                  at Object.oncomplete (fs.js:107:15)
```

Some info about my env : 

```
$ node --version
v0.10.5

$ npm --version
1.2.18
```

**Comment by Esya** [comment]
Also, tried to `console.log('/api/'+plugin,docRoot);`
In `api.on("staticContribution", function(plugin) {` but everything seems fine, the paths are right.

**Comment by Esya** [comment]
Okay, fixed, it's a problem with the version of socket.io

0.9.10 conflicts with express, 0.9.16 doesn't.
